# Adapts bgruening/galaxy-stable for use on a ogs-cluster

from bgruening/galaxy-stable:17.05

Maintainer test@example.com

USER root

RUN echo "192.168.99.100 ogs-cluster-head" >> /etc/hosts

CMD ["/usr/bin/startup"]
