---
# -----
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-launcher.
#
# galaxy-launcher is free software: you can redistribute it
# and/or modify it under the terms of the MIT License (Expat) as
# published by the Open Source initiative.
#
# You should have received a copy of the MIT License (Expat)
# along with galaxy-launcher. If not, see
# <https://opensource.org/licenses/MIT>.
# .....

# Tasks for testing migration

#- name: copy running instance files to test location
#  copy module is not used because remote_src does not support recursive copying.
#  Please enable the module if it is supported in future versions of anisble
#  copy:
#    remote_src: True

- name: Create test location directory
  file:
    path: "{{galaxy_docker_upgrade_test_settings.galaxy_docker_export_location}}"
    state: "directory"
    mode: "{{galaxy_docker_export_location_mode}}"

- name: create subfolders
  file:
    state: directory
    path: "{{galaxy_docker_upgrade_test_settings.galaxy_docker_export_location}}/{{item.dest}}"
    mode: "{{item.mode | default(omit)}}"
  with_items:
    - src: "galaxy-central/config"
      dest: "galaxy-central"
    - src: "postgresql"
      dest: ""
      mode: "0775"

- name: Copy running instance files to test location
  command: "cp -p -R {{src}} {{dest}}"
  args:
    creates: "{{dest}}"
  vars:
    src: "{{galaxy_docker_export_location}}/{{item.src}}"
    dest: "{{galaxy_docker_upgrade_test_settings.galaxy_docker_export_location}}/{{item.dest}}"
  with_items:
    - src: "galaxy-central/config"
      dest: "galaxy-central"

- import_tasks: copy_database.yml
  become: "{{galaxy_docker_become}}"
  become_user: "{{galaxy_docker_database_user}}"
  vars:
    ansible_user: "{{galaxy_docker_database_ssh_user}}"
    ansible_ssh_private_key_file: "{{galaxy_docker_database_user_private_key}}"

- name: Set test upgrade parameters for the docker container
  set_fact:
    "{{item.key}}": "{{item.value}}"
  with_dict: "{{galaxy_docker_upgrade_test_settings}}"

- name: Set container defaults succesfull?
  debug:
    var: galaxy_brand
    verbosity: 1
