---
# -----
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
#
# galaxy-docker-ansible is free software: you can redistribute it
# and/or modify it under the terms of the MIT License (Expat) as
# published by the Open Source initiative.
#
# You should have received a copy of the MIT License (Expat)
# along with galaxy-docker-ansible. If not, see
# <https://opensource.org/licenses/MIT>.
# .....

# This task decides wich sub-tasks should be run based on the boolean variables.
# The order should represent the order in which tasks are ideally done.

# tasks file for installdocker

- name: Create docker default location
  file:
    state: directory
    path: "{{ installdocker_default_location }}"

- name: Set symbolic link for default location
  file:
    state: link
    path: /var/lib/docker
    src: "{{ installdocker_default_location }}"
  when: "not installdocker_default_location=='/var/lib/docker'"

# Distrospecific. Only disto.
# ansible_distribution_version specific things should be handled down the line
- name: Start distribution specific installation
  include_tasks: "{{role_path}}/tasks/distributions/{{ansible_distribution}}.yml"


# General postinstall
- name: install required python_packages
  package:
    name: "{{installdocker_python_packages}}"
    state: present

- name: Install required PIP packages
  pip:
    name: "{{ installdocker_pip_packages }}"
    state: present

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started
  notify: test docker service

# Make sure docker installation is tested before other roles are started
- meta: flush_handlers
